import type React from "react"
import CashierTemplate from "@/components/cashierTemplate"
import MenuList from "../menuList"

export const metadata = {
  title: "Dashboard | Ordering System",
  description: "Generated by create next app",
}

type PropsLayout = {
  children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
  return (
    <CashierTemplate title="Dashboard" id="dashboard" menuList={MenuList}>
      {children}
    </CashierTemplate>
  )
}

export default RootLayout

