import CashierTemplate from "@/components/cashierTemplate"
import MenuList from "../menuList"
import { ToastContainer } from "react-toastify"

export const metadata = {
    title: 'Menu | Ordering System',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}
const RootLayout = ({ children }: PropsLayout) => {
    return (
        <CashierTemplate title="Menu" id="Menu" menuList={MenuList}>
            {children}
                <ToastContainer containerId={`toastMenu`} />
        </CashierTemplate>
    )
}
export default RootLayout