import ManagerTemplate from "@/components/managerTemplate"
import MenuList from "../menuList"

export const metadata = {
    title: 'Pesan makanan | Ordering System',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}
const RootLayout = ({ children }: PropsLayout) => {
    return (
        <ManagerTemplate title="Pesan makanan" id="pesan_makanan" menuList={MenuList}>
            {children}
        </ManagerTemplate>
    )
}
export default RootLayout