import type React from "react"
import CashierTemplat from "@/components/cashierTemplate"
import MenuList from "../menuList"
import { ToastContainer } from "react-toastify"

export const metadata = {
  title: "Order | Ordering System",
  description: "Generated by create next app",
}

type PropsLayout = {
  children: React.ReactNode
}
const RootLayout = ({ children }: PropsLayout) => {
  return (
    <CashierTemplat title="Pesan makanan" id="pesan_makanan" menuList={MenuList}>
            <ToastContainer containerId="toastOrder" position="top-right" />

      {children}
    </CashierTemplat>
  )
}
export default RootLayout

