import CashierTemplate from "@/components/cashierTemplate"
import MenuList from "../menuList"
import { ToastContainer } from "react-toastify"

export const metadata = {
    title: 'Menu_favorite | Ordering System',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}
const RootLayout = ({ children }: PropsLayout) => {
    return (
        <CashierTemplate title="Menu favorite" id="menu_favorite" menuList={MenuList}>
            {children}
            <ToastContainer containerId={`toastUser`} />
        </CashierTemplate>
    )
}
export default RootLayout